# Site settings
title: 시 모음
description: "내가 좋아하는 시 모음"
url: "http://localhost:4000/"
author:
  name: "me"
  email: ""
  url: "https://thereviewindex.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
permalink: /:title
paginate: 4
paginate_path: /:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
